# Generated by Django 3.2 on 2021-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre de Cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tfno',
            field=models.CharField(max_length=9, verbose_name='Teléfono'),
        ),
    ]
